export const mockProductPriceQuantityTotal = [
    {
        id: "1",
        productName: 'R.B',
        productSize: '2 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id: "2",
        productName: 'R.B Dram',
        productSize: '3000 ltr',
        productPrice: 3200,
        productQuantity: 120,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id: "3",
        productName: 'Tripti',
        productSize: '1 ltr',
        productPrice: 100,
        productQuantity: 3,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id: "4",
        productName: 'Bashundhara',
        productSize: '2 ltr',
        productPrice: 1000,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id: "5",
        productName: 'Tripti',
        productSize: '5 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id: "6",
        productName: 'R.B',
        productSize: '2/1 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id: "7",
        productName: 'Teer',
        productSize: '2 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id: "8",
        productName: 'R.B',
        productSize: '2 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id: "9",
        productName: 'R.B',
        productSize: '2 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    }
]

export const mockCardWithGoods = [
    {
        id: 1,
        name: 'R.B',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 101,
                brand: 'R.B',
                name: '5 ltr',
                price: 530,
                quantity: 800,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
            {
                id: 102,
                brand: 'R.B',
                name: '2 ltr',
                price: 240,
                quantity: 280,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
            {
                id: 103,
                brand: 'R.B',
                name: '1 ltr',
                price: 128,
                quantity: 350,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
            {
                id: 104,
                brand: 'R.B',
                name: '500 ml',
                price: 65,
                quantity: 1234,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
        ],
    },
    {
        id: 2,
        name: 'Tripti',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 201,
                brand: 'Tripti',
                name: '5 ltr',
                price: 530,
                quantity: 800,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
            {
                id: 202,
                brand: 'Tripti',
                name: '2 ltr',
                price: 240,
                quantity: 280,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
            {
                id: 203,
                brand: 'Tripti',
                name: '1 ltr',
                price: 128,
                quantity: 350,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
            {
                id: 204,
                brand: 'Tripti',
                name: '500 ml',
                price: 65,
                quantity: 1234,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
        ],
    },
    {
        id: 3,
        name: 'Bashundhara',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 301,
                brand: 'Bashundhara',
                name: '5 ltr',
                price: 530,
                quantity: 800,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
            {
                id: 302,
                brand: 'Bashundhara',
                name: '2 ltr',
                price: 240,
                quantity: 280,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
            {
                id: 303,
                brand: 'Bashundhara',
                name: '1 ltr',
                price: 128,
                quantity: 350,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
            {
                id: 304,
                brand: 'Bashundhara',
                name: '500 ml',
                price: 65,
                quantity: 1234,
                imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
            },
        ],
    },
]

export const mockCart = []
