export const mockProductPriceQuantityTotal = [
    {
        id:"1",
        productName: 'R.B',
        productSize: '2 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id:"2",
        productName: 'R.B Dram',
        productSize: '3000 ltr',
        productPrice: 3200,
        productQuantity: 120,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id:"3",
        productName: 'Tripti',
        productSize: '1 ltr',
        productPrice: 100,
        productQuantity: 3,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id:"4",
        productName: 'Bashundhara',
        productSize: '2 ltr',
        productPrice: 1000,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id:"5",
        productName: 'Tripti',
        productSize: '5 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id:"6",
        productName: 'R.B',
        productSize: '2/1 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id:"7",
        productName: 'Teer',
        productSize: '2 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id:"8",
        productName: 'R.B',
        productSize: '2 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
    },
    {
        id:"9",
        productName: 'R.B',
        productSize: '2 ltr',
        productPrice: 100,
        productQuantity: 2,
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg', 
    }
]

export const mockCardWithGoods = [
    {
        id:1,
        name: 'R.B',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 11,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 12,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 13,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 14,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:2,
        name: 'Tripti',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 21,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 22,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 23,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 24,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:3,
        name: 'Bashundhara',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 31,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 32,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 33,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 34,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:1,
        name: 'R.B',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 11,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 12,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 13,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 14,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:2,
        name: 'Tripti',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 21,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 22,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 23,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 24,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:3,
        name: 'Bashundhara',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 31,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 32,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 33,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 34,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:1,
        name: 'R.B',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 11,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 12,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 13,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 14,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:2,
        name: 'Tripti',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 21,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 22,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 23,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 24,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:3,
        name: 'Bashundhara',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 31,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 32,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 33,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 34,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:1,
        name: 'R.B',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 11,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 12,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 13,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 14,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:2,
        name: 'Tripti',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 21,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 22,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 23,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 24,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
    {
        id:3,
        name: 'Bashundhara',
        imageUrl: 'https://i.ibb.co/b5qyhvM/fresh-oil.jpg',
        subProducts: [
            {
                id: 31,
                name: '5 ltr',
                price: 530,
                quantity: 800,
            },
            {
                id: 32,
                name: '2 ltr',
                price: 240,
                quantity: 280,
            },
            {
                id: 33,
                name: '1 ltr',
                price: 128,
                quantity: 350,
            },
            {
                id: 34,
                name: '500 ml',
                price: 65,
                quantity: 1234,
            },
        ],
    },
]

export const mockCart = []
